### ISSUE TITLE
Code for BERT

### ISSUE THREAD

**Issue by tkorach** [TharinduDR/Simple-Sentence-Similarity#1]
From a brief search, it is not clear where is the code for testing BERT embeddings. This is specifically interesting since BERT embeddings are known to be not very suitable for simple similarity calculation: 
https://github.com/google-research/bert/issues/164#issuecomment-441324222

> I'm  not sure what these vectors are, since BERT does not generate  meaningful sentence vectors. It seems that this is is doing average  pooling over the word tokens to get a sentence vector, but we never  suggested that this will generate meaningful sentence representations.  And even if they are decent representations when fed into a DNN trained  for a downstream task, it doesn't mean that they will be meaningful in  terms of cosine distance. (Since cosine distance is a linear space where  all dimensions are weighted equally).

A solution for this issue will be very useful.

**Comment by TharinduDR** [comment]
Hi @tkorach 
Yes, What I discovered is that BERT embeddings are not good in averaging method and word moving distance method. However, it performs better than word embeddings in smooth inverse frequency. I have not included the BERT experiments here since I did the experiments in co-lab.

However if you just change the lines here you can run BERT experiments - 

`from flair.embeddings import ELMoEmbeddings` 
`elmo = ELMoEmbeddings('original')`

Change it to BERTEmbeddings. Let me know if you get any problems.
